"""add enum and name for user

Revision ID: 7c0f574a97f9
Revises: d0b0f1057a65
Create Date: 2024-10-09 09:21:36.823876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0f574a97f9'
down_revision: Union[str, None] = 'd0b0f1057a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_item', sa.Column('status', sa.Enum('Todo', 'Processing', 'Done', name='item_status'), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('todo_item', 'status')
    # ### end Alembic commands ###
