"""add enum type

Revision ID: d038cda717e2
Revises: d0b0f1057a65
Create Date: 2024-10-08 16:07:55.910040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd038cda717e2'
down_revision: Union[str, None] = 'd0b0f1057a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_item', sa.Column('status', sa.Enum('Todo', 'Processing', 'Done', name='item_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_item', 'status')
    # ### end Alembic commands ###
